In [1]:
# Here initially we will overfit the data
# Next we will use a drop out layer to understand how dropping the biased layers improves the accuracy of the model.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("sonar.csv") # Use sonar1 to check how missing values affect the  outputs

In [4]:
df.head() # Some weird values at columns. 1st row being considered as heading to the columns. Avoid that using next cell.

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [5]:
df = pd.read_csv("sonar.csv",header = None) # Header = None. Takes index numbers as columns if column not provided in csv.

In [6]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [7]:
df.shape

(208, 61)

In [8]:
list(df.isna().sum()) # finding the empty cells.

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [9]:
df.columns #finding the index of all columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [10]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [11]:
X = df.drop(60, axis = 1)
y = df[60]

In [12]:
X.shape

(208, 60)

In [13]:
y.shape

(208,)

In [14]:
y[74] # comparing with values below after hotcoding

'R'

In [15]:
y[162]

'M'

__Now y is in the form of R and M. we need either 0 or 1. R --> 1 and M --> 0__

    We have just two categories here R and M. So we need not divide them in individual columns. We can get the output using 1 or 0. If there was a third category we would have done one hot encoding and individual columns were needed to be created then.

In [16]:
y = pd.get_dummies(y,drop_first= True) #Assigns column the name of first element and marks as 1 at the index of that element.
y.sample(5)

R
184  0
0    1
13   1
64   1
114  0

In [17]:
y.iloc[[27,112,102],[0]] # Just a simple check.

R
27   1
112  0
102  0

In [18]:
y.value_counts() # Compare above R= 97 M=111

R
0    111
1     97
dtype: int64

__SPLITTING__

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.25,random_state= 1)

In [20]:
X_train.shape

(156, 60)

In [21]:
X_test.shape

(52, 60)

In [22]:
y_train.shape

(156, 1)

In [23]:
y_test.shape

(52, 1)

__Predicting using tensorflow__

In [24]:
import tensorflow as tf
from tensorflow import keras

In [25]:
# Using batch GD- Logistic regression problem- Overfitting the data to understand dropout regularization.
# Compare accuracy with the dropout layers in the next section.
model = keras.Sequential([
    keras.layers.Dense(60,input_shape = (60,), activation = 'relu'),
    keras.layers.Dense(30,activation= 'relu' ),
    keras.layers.Dense(15,activation= 'relu' ),
    keras.layers.Dense(1,activation= 'sigmoid')
])

model.compile (loss = 'binary_crossentropy',optimizer= 'adam', metrics =['accuracy'])

In [26]:
model.fit(X_train,y_train, epochs = 100, batch_size = 8) # model overfitted accuracy 100%

Epoch 1/100
20/20 [==============================] - 1s 3ms/step - loss: 0.6855 - accuracy: 0.5321
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6657 - accuracy: 0.5769
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6416 - accuracy: 0.7244
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6187 - accuracy: 0.7051
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5937 - accuracy: 0.7308
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5520 - accuracy: 0.7436
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5085 - accuracy: 0.8141
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4967 - accuracy: 0.7500
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4520 - accuracy: 0.8013
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4273 - accuracy: 0.8205
Epoch 11/

20/20 [==============================] - 0s 3ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0054 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0053 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 93/100


In [27]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 1.0376 - accuracy: 0.7885


[1.0375573635101318, 0.7884615659713745]

In [28]:
y_pred = model.predict(X_test)

2/2 [==============================] - 0s 4ms/step


In [29]:
y_pred = y_pred.reshape(-1) # Converting to 1d from 2d

In [30]:
y_pred.shape #predicted values from sigmoid 

(52,)

In [31]:
y_pred = np.round(y_pred) # Converts values <0.5 AND 0.5 TO 0. 0.5 > TO 1

In [32]:
y_pred

array([0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.], dtype=float32)

In [33]:
arr = np.array([0.99,0.89,0.67,0.48,0.51])

In [34]:
arr

array([0.99, 0.89, 0.67, 0.48, 0.51])

In [35]:
np.round(arr)

array([1., 1., 1., 0., 1.])

In [36]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.93      0.82        27
           1       0.89      0.64      0.74        25

    accuracy                           0.79        52
   macro avg       0.81      0.78      0.78        52
weighted avg       0.81      0.79      0.78        52



__Using the dropout for better accuracy__

In [37]:
# Introducing the dropout layers that removes bias to some extent that impoves the accuracy
model1 = keras.Sequential([
    keras.layers.Dense(60,input_shape = (60,), activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,activation= 'relu' ),
     keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation= 'relu' ),
     keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation= 'sigmoid')
])

model1.compile (loss = 'binary_crossentropy',optimizer= 'adam', metrics =['accuracy'])

In [38]:
model1.fit(X_train,y_train, epochs = 100, batch_size = 8) 
# overfitting avoided by introducing drop out layers that removed the bias. Accuracy = 91 % 

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7571 - accuracy: 0.4872
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7109 - accuracy: 0.4615
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6916 - accuracy: 0.5641
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7029 - accuracy: 0.5385
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6916 - accuracy: 0.5064
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.5256
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6841 - accuracy: 0.5321
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7038 - accuracy: 0.4936
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6837 - accuracy: 0.5641
Epoch 10/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6783 - accuracy: 0.5449
Epoch 11/

20/20 [==============================] - 0s 3ms/step - loss: 0.3728 - accuracy: 0.8590
Epoch 84/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3149 - accuracy: 0.8910
Epoch 85/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3588 - accuracy: 0.8590
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3626 - accuracy: 0.8654
Epoch 87/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3399 - accuracy: 0.8846
Epoch 88/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2744 - accuracy: 0.9167
Epoch 89/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2967 - accuracy: 0.8654
Epoch 90/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3357 - accuracy: 0.8846
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2860 - accuracy: 0.8910
Epoch 92/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3165 - accuracy: 0.8974
Epoch 93/100


In [39]:
model1.evaluate(X_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.5190 - accuracy: 0.7885


[0.518975555896759, 0.7884615659713745]

In [40]:
y_pred1 = model1.predict(X_test)

2/2 [==============================] - 0s 3ms/step


In [41]:
y_pred1 = np.round(y_pred1.reshape(-1)) # Converting to 1d from 2d

In [42]:
y_pred1

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.], dtype=float32)

__Comparing the precision recall and f1 score after and before dropout__

In [43]:
from sklearn.metrics import confusion_matrix, classification_report ##After Dropout
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.75      0.89      0.81        27
           1       0.85      0.68      0.76        25

    accuracy                           0.79        52
   macro avg       0.80      0.78      0.78        52
weighted avg       0.80      0.79      0.79        52



In [44]:
from sklearn.metrics import confusion_matrix, classification_report  ##Before Dropout
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.93      0.82        27
           1       0.89      0.64      0.74        25

    accuracy                           0.79        52
   macro avg       0.81      0.78      0.78        52
weighted avg       0.81      0.79      0.78        52

