In [1]:
import tensorflow as tf

In [2]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False) # import images

In [3]:
for file in images_ds.take(5): # First five images from images_ds(probably cat only : first folder)
    print(file.numpy())

b'images\\cat\\10 Cat Exercises Your Pet Will Enjoy.jpg'
b'images\\cat\\10 Facts about Cats - FOUR PAWS.jpg'
b'images\\cat\\10_000_ Best Cat Photos \xc2\xb7 100_ Free (1).jpeg'
b'images\\cat\\10_000_ Best Cat Photos \xc2\xb7 100_ Free (1).jpg'
b'images\\cat\\10_000_ Best Cat Photos \xc2\xb7 100_ Free (2).jpeg'


In [4]:
class_names = ["cat","dog"]

In [5]:
import os

In [6]:
os.path.sep

'\\'

In [7]:
tf.strings.split('images\\dog\\43 Best Small Dog Breeds \xe2\x80\x94 Popular Toy (1).jpg',os.path.sep)

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'images', b'dog',
       b'43 Best Small Dog Breeds \xc3\xa2\xc2\x80\xc2\x94 Popular Toy (1).jpg'],
      dtype=object)>

In [8]:
tf.strings.split('images\\dog\\43 Best Small Dog Breeds \xe2\x80\x94 Popular Toy (1).jpg',os.path.sep)[-2]

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [9]:
tf.strings.split('images\\dog\\43 Best Small Dog Breeds \xe2\x80\x94 Popular Toy (1).jpg',os.path.sep)[-1]

<tf.Tensor: shape=(), dtype=string, numpy=b'43 Best Small Dog Breeds \xc3\xa2\xc2\x80\xc2\x94 Popular Toy (1).jpg'>

In [10]:
# We will be using these functions inside tf pipelines. So make sure they are compatible. Else error will show up.
#.split needs to be called in tf.strings.split (only .split is not there)
def get_label(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-2]  

In [11]:
def get_path(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-1]  

In [12]:
get_label

<function __main__.get_label(file_path)>

In [13]:
get_label('images\\dog\\43 Best Small Dog Breeds \xe2\x80\x94 Popular Toy (1).jpg')

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [14]:
# Generating Combined image and labels
def process_image(file_path):
    label = get_label(file_path)
    path_name = get_path(file_path)
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img,[128,128])
    return img,label,path_name

In [15]:
for image,label,path_name in images_ds.map(process_image):
    print(image)
    print(label)
    print(path_name)

tf.Tensor(
[[[220.53418  227.53418  237.28418 ]
  [193.33594  205.21094  214.58594 ]
  [204.61621  210.61621  222.61621 ]
  ...
  [147.45898  122.458984 102.458984]
  [146.58496  121.58496  101.58496 ]
  [137.20801  112.20801   90.20801 ]]

 [[196.28711  206.27344  216.28027 ]
  [195.72461  208.72461  217.72461 ]
  [158.34473  166.34473  177.34473 ]
  ...
  [147.00781  122.00781  102.00781 ]
  [145.99512  120.99512  100.99512 ]
  [142.       117.        95.      ]]

 [[197.44824  207.33789  217.22754 ]
  [187.57227  200.82715  209.40234 ]
  [207.31738  216.67676  226.99707 ]
  ...
  [145.67969  120.03906  100.359375]
  [144.93457  119.293945  99.61426 ]
  [140.95508  116.7959    95.15625 ]]

 ...

 [[158.27441  148.27441  139.27441 ]
  [165.625    152.625    143.625   ]
  [161.32031  148.32031  139.32031 ]
  ...
  [186.625    177.375    167.      ]
  [182.73438  176.73438  164.73438 ]
  [171.83496  161.83496  152.83496 ]]

 [[160.00781  151.00781  144.00781 ]
  [162.99219  152.99219  1

tf.Tensor(
[[[29.5 19.5 17.5]
  [22.5 17.5 11.5]
  [27.  19.  16. ]
  ...
  [24.  21.  16. ]
  [30.5 22.5 19.5]
  [24.5 21.5 16.5]]

 [[25.  20.  16. ]
  [27.5 19.5 16.5]
  [26.5 21.5 17.5]
  ...
  [27.  22.  19. ]
  [27.  22.  18. ]
  [29.5 21.5 19.5]]

 [[24.  21.  16. ]
  [24.  21.  16. ]
  [26.  21.  15. ]
  ...
  [35.  27.  24. ]
  [21.  20.  16. ]
  [24.5 21.5 16.5]]

 ...

 [[72.  58.  55. ]
  [83.  69.  68. ]
  [88.5 70.5 70.5]
  ...
  [55.5 47.5 45.5]
  [60.5 49.5 45.5]
  [52.5 47.5 44.5]]

 [[67.5 57.5 56.5]
  [82.5 68.5 67.5]
  [84.  70.  69. ]
  ...
  [53.5 48.5 44.5]
  [56.5 44.5 44.5]
  [51.5 46.5 42.5]]

 [[76.  61.  58. ]
  [78.  67.  63. ]
  [81.  72.  67. ]
  ...
  [51.5 41.5 42.5]
  [67.  51.  51. ]
  [56.5 51.5 47.5]]], shape=(128, 128, 3), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'10_000_ Best Cat Photos \xc2\xb7 100_ Free.jpg', shape=(), dtype=string)
tf.Tensor(
[[[2.96875000e-01 5.31250000e-01 4.14062500e-01]
  [7.00000000e+00 6.9609375

tf.Tensor(
[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]], shape=(128, 128, 3), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'5 things that scare and stress your cat.jpg', shape=(), dtype=string)
tf.Tensor(
[[[235.21277 237.21277 234.21277]
  [234.      235.      230.     ]
  [236.    

tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'Cat Images _ Free Vectors_ Stock Photos (2).jpg', shape=(), dtype=string)
tf.Tensor(
[[[255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  ...
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]]

 [[255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  ...
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]]

 [[255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  ...
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]]

 ...

 [[255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  ...
  [255.      255.      255.     ]
  [255.      255.      255.     ]
  [255.      255.      255.     ]]

 [[255.

tf.Tensor(
[[[183.     176.     158.    ]
  [187.625  180.625  164.25  ]
  [188.1875 181.5625 163.375 ]
  ...
  [180.25   175.     151.1875]
  [178.     172.     150.    ]
  [175.75   173.1875 150.75  ]]

 [[182.4375 177.875  154.5625]
  [181.125  177.     158.    ]
  [188.5625 180.4375 163.    ]
  ...
  [174.5625 169.5625 147.5625]
  [175.5625 169.5625 145.5625]
  [177.125  172.125  152.125 ]]

 [[184.3125 176.125  157.1875]
  [186.     175.     155.    ]
  [185.125  177.125  158.    ]
  ...
  [169.3125 167.3125 142.3125]
  [177.9375 171.9375 149.9375]
  [177.9375 172.9375 150.9375]]

 ...

 [[ 17.      70.1875   2.    ]
  [ 25.3125  82.375   11.0625]
  [ 41.5    103.1875  20.5625]
  ...
  [ 13.875   69.8125   0.    ]
  [ 11.      60.875    0.    ]
  [ 17.375   84.375    5.375 ]]

 [[ 20.      92.5625   4.875 ]
  [ 31.8125  96.375   13.5   ]
  [ 16.875   78.75     8.3125]
  ...
  [ 25.5     84.6875  11.0625]
  [ 23.      81.       5.875 ]
  [ 22.8125  94.875    9.6875]]

 [[ 15.8125  

tf.Tensor(
[[[175.21216  165.21216  138.21216 ]
  [177.27002  171.27002  145.27002 ]
  [185.63574  174.63574  152.63574 ]
  ...
  [132.53271  111.0271    96.862305]
  [156.51318  139.51318  123.51318 ]
  [164.16382  152.06226  131.20679 ]]

 [[168.92969  163.65503  131.65503 ]
  [185.65015  176.65015  147.40796 ]
  [186.646    178.646    158.63477 ]
  ...
  [132.60278  115.60278   99.60278 ]
  [138.73022  121.79639  111.308105]
  [142.93774  125.01343  110.975586]]

 [[174.40845  163.03345  137.65063 ]
  [177.9375   172.9375   143.47266 ]
  [184.82056  178.82056  156.82056 ]
  ...
  [126.69336  111.28662   92.48999 ]
  [133.41602  122.416016 104.416016]
  [128.40576  116.96826  100.03076 ]]

 ...

 [[178.30908  168.97461  163.51685 ]
  [185.38281  169.25781  169.25781 ]
  [192.68042  183.68042  178.68042 ]
  ...
  [230.       233.       238.      ]
  [231.       235.       238.      ]
  [230.51318  234.51318  237.51318 ]]

 [[185.8789   179.9414   176.2539  ]
  [189.8125   178.8125   1

tf.Tensor(
[[[186.26562  185.39062  183.39062 ]
  [187.1875   187.1875   185.1875  ]
  [179.75781  176.01562  172.92969 ]
  ...
  [198.875    203.05469  197.32812 ]
  [193.89844  199.14844  194.44531 ]
  [197.11719  202.11719  198.11719 ]]

 [[182.27344  182.27344  180.27344 ]
  [190.17969  190.17969  188.17969 ]
  [177.39844  173.02344  168.71094 ]
  ...
  [200.00781  204.23438  198.49219 ]
  [196.88281  201.88281  196.02344 ]
  [197.25     202.25     196.25    ]]

 [[176.3125   175.3125   171.3125  ]
  [192.4375   192.4375   190.4375  ]
  [185.88281  185.88281  183.88281 ]
  ...
  [198.       203.       199.      ]
  [195.50781  200.50781  196.50781 ]
  [197.       202.       198.      ]]

 ...

 [[197.375    202.375    206.375   ]
  [201.0625   206.0625   210.0625  ]
  [197.57031  202.57031  206.57031 ]
  ...
  [121.19531  120.19531  116.19531 ]
  [149.98438  150.60938  145.79688 ]
  [149.25     147.125    143.5     ]]

 [[204.97656  209.97656  213.97656 ]
  [207.375    212.375    2

tf.Tensor(
[[[ 76.25  83.75  74.25]
  [ 68.5   78.    67.  ]
  [ 64.    72.    61.  ]
  ...
  [104.5   66.5   55.5 ]
  [102.5   63.5   51.  ]
  [103.    65.    52.  ]]

 [[ 89.    96.5   87.  ]
  [ 73.5   83.5   74.5 ]
  [ 71.    81.    72.5 ]
  ...
  [105.    67.    56.  ]
  [105.    67.    54.  ]
  [105.5   67.5   56.5 ]]

 [[ 91.    98.    90.5 ]
  [ 82.75  90.25  80.75]
  [ 83.75  89.75  85.75]
  ...
  [105.    69.    57.  ]
  [107.    69.    58.  ]
  [107.    69.    58.  ]]

 ...

 [[167.   154.   146.  ]
  [167.   154.   146.  ]
  [169.   156.   148.  ]
  ...
  [179.   162.   155.  ]
  [178.25 160.75 155.25]
  [178.   163.   156.  ]]

 [[163.5  150.5  144.5 ]
  [164.   151.   143.  ]
  [165.   152.   145.  ]
  ...
  [176.   159.   152.  ]
  [175.5  158.5  151.5 ]
  [175.   160.   153.  ]]

 [[156.5  143.5  137.5 ]
  [160.   147.   139.5 ]
  [161.   148.   141.  ]
  ...
  [173.   158.   153.  ]
  [173.   158.   153.  ]
  [170.75 157.75 151.25]]], shape=(128, 128, 3), dtype=float32

tf.Tensor(
[[[ 74.        94.        57.      ]
  [ 73.484375  93.484375  56.484375]
  [ 76.        98.        60.      ]
  ...
  [ 75.        95.        58.      ]
  [ 74.828125  94.828125  57.828125]
  [ 72.        92.        55.      ]]

 [[ 74.        96.        58.      ]
  [ 75.9375    98.        58.8125  ]
  [ 77.75      97.75      60.75    ]
  ...
  [ 75.046875  97.046875  59.046875]
  [ 75.        95.        58.      ]
  [ 74.        94.        57.      ]]

 [[ 74.        96.        58.      ]
  [ 77.75      98.75      59.75    ]
  [ 79.546875  99.546875  62.546875]
  ...
  [ 74.4375    96.4375    58.4375  ]
  [ 74.75      94.75      57.75    ]
  [ 76.        96.        59.      ]]

 ...

 [[ 81.09375   85.109375  45.      ]
  [ 83.        85.        46.      ]
  [ 72.3125    81.        46.4375  ]
  ...
  [ 89.375     92.671875  51.609375]
  [115.4375    93.5625    51.      ]
  [ 93.734375  93.46875   51.234375]]

 [[ 69.5       81.25      49.      ]
  [ 73.953125  77.953125  

tf.Tensor(
[[[1.34582520e-02 2.25653229e+01 2.65653229e+01]
  [0.00000000e+00 1.47838745e+01 2.27838745e+01]
  [1.64843750e+00 1.41547394e+01 2.31547394e+01]
  ...
  [3.49166870e-01 1.69227600e+01 2.39227600e+01]
  [7.69668579e+00 2.29089355e+01 2.99089355e+01]
  [4.17469482e+01 3.52000732e+01 2.92636566e+01]]

 [[2.90562439e+00 2.56289368e+01 3.06289368e+01]
  [4.38671875e+00 1.82655945e+01 2.72655945e+01]
  [1.12765503e+00 1.21021881e+01 2.11021881e+01]
  ...
  [7.01873779e-01 2.42006226e+01 2.82006226e+01]
  [0.00000000e+00 1.07050323e+01 1.47050323e+01]
  [6.59184265e+00 3.92793427e+01 4.07051239e+01]]

 [[4.78817749e+00 2.77467194e+01 3.37467194e+01]
  [9.95330811e-02 1.26957855e+01 2.16957855e+01]
  [6.22994995e+00 1.61770782e+01 2.61770782e+01]
  ...
  [0.00000000e+00 2.31403656e+01 2.81757812e+01]
  [1.81274414e-02 1.72960968e+01 2.42960968e+01]
  [4.75932312e+00 3.76905212e+01 4.26905212e+01]]

 ...

 [[9.32184906e+01 8.82184906e+01 6.82184906e+01]
  [1.06104523e+02 9.51045227

tf.Tensor(
[[[ 39.25  51.25  27.25]
  [ 37.25  49.25  25.25]
  [ 34.75  46.75  22.75]
  ...
  [ 33.25  31.25  11.75]
  [ 29.5   28.5    8.5 ]
  [ 25.75  24.75   6.25]]

 [[ 43.5   58.5   32.5 ]
  [ 42.25  54.25  30.25]
  [ 38.5   50.5   26.5 ]
  ...
  [ 24.75  27.75   8.75]
  [ 20.    23.     6.  ]
  [ 17.5   20.     4.5 ]]

 [[ 51.75  65.75  39.75]
  [ 46.75  59.75  33.75]
  [ 42.75  54.75  30.75]
  ...
  [ 21.75  24.75   7.75]
  [ 13.75  17.75   2.75]
  [ 10.25  14.75   3.25]]

 ...

 [[140.25 170.25 103.25]
  [117.5  147.5   77.5 ]
  [175.   195.25 126.25]
  ...
  [130.75 160.25  83.75]
  [158.25 171.75 102.25]
  [135.   161.    93.5 ]]

 [[132.25 156.25  82.25]
  [168.   191.   123.  ]
  [149.25 175.25 105.5 ]
  ...
  [143.   168.25  95.  ]
  [142.   165.75  99.  ]
  [138.25 164.25  90.75]]

 [[127.75 153.75  82.75]
  [128.75 155.    84.  ]
  [162.   176.5  115.  ]
  ...
  [132.25 159.    86.75]
  [147.   169.   105.25]
  [172.5  190.75 134.5 ]]], shape=(128, 128, 3), dtype=float32

tf.Tensor(
[[[ 32.333984  28.333984  19.333984]
  [ 31.560547  26.560547  20.560547]
  [ 33.59375   24.59375   16.71875 ]
  ...
  [ 38.        29.        20.      ]
  [ 38.21875   28.21875   19.21875 ]
  [ 34.59375   27.59375   17.59375 ]]

 [[ 33.        26.        18.      ]
  [ 32.        27.        21.      ]
  [ 37.        28.        19.      ]
  ...
  [ 38.        29.        20.      ]
  [ 35.53125   26.53125   19.53125 ]
  [ 31.59375   27.59375   16.59375 ]]

 [[ 37.1875    28.1875    21.1875  ]
  [ 34.59375   30.03125   19.21875 ]
  [ 35.80664   27.18164   21.99414 ]
  ...
  [ 31.394531  28.019531  21.207031]
  [ 36.146484  29.146484  19.146484]
  [ 33.88867   29.888672  20.888672]]

 ...

 [[127.375    102.        71.1875  ]
  [109.4375    92.625     66.8125  ]
  [108.22461   89.22461   57.59961 ]
  ...
  [164.59961  133.23828   92.08789 ]
  [177.73047  143.20898  102.990234]
  [131.42383  117.98633   84.69141 ]]

 [[ 91.3125    68.375     47.6875  ]
  [119.57422   88.77539   

tf.Tensor(
[[[179.55469  181.55469  180.30469 ]
  [181.125    183.125    182.125   ]
  [182.03125  184.03125  181.03125 ]
  ...
  [175.89844  179.89844  178.89844 ]
  [175.91406  179.91406  178.91406 ]
  [179.69531  181.69531  180.69531 ]]

 [[177.92188  179.92188  178.92188 ]
  [177.29688  179.29688  178.29688 ]
  [186.88281  188.88281  185.88281 ]
  ...
  [170.78125  174.78125  173.78125 ]
  [176.42969  178.42969  175.80469 ]
  [171.21875  174.96875  173.96875 ]]

 [[177.47656  179.47656  178.22656 ]
  [180.45312  182.45312  179.45312 ]
  [181.53906  183.53906  180.53906 ]
  ...
  [177.24219  179.24219  178.24219 ]
  [171.07812  175.07812  174.07812 ]
  [176.5625   180.5625   179.5625  ]]

 ...

 [[168.70312  176.70312  178.70312 ]
  [171.07812  176.07812  179.07812 ]
  [169.64062  177.64062  179.64062 ]
  ...
  [ 32.09375   29.96875   26.34375 ]
  [ 29.84375   28.84375   26.84375 ]
  [ 35.789062  32.046875  28.960938]]

 [[166.92188  172.41406  175.25    ]
  [168.53906  176.53906  1

tf.Tensor(
[[[252.   249.   244.  ]
  [252.   249.   244.  ]
  [251.5  248.5  243.5 ]
  ...
  [253.   249.   246.  ]
  [253.   249.   246.  ]
  [253.   249.   246.  ]]

 [[252.   249.   244.  ]
  [252.   249.   244.  ]
  [252.   249.   244.  ]
  ...
  [252.5  248.5  245.5 ]
  [252.   248.   245.  ]
  [253.   249.   246.  ]]

 [[252.   249.   244.  ]
  [252.   249.   244.  ]
  [252.   249.   244.  ]
  ...
  [253.   249.   246.  ]
  [253.   249.   246.  ]
  [253.   249.   246.  ]]

 ...

 [[251.   246.   240.  ]
  [250.   245.   239.  ]
  [250.   245.   239.  ]
  ...
  [253.   249.   246.  ]
  [251.   250.   245.  ]
  [253.   249.   246.  ]]

 [[251.   246.   240.  ]
  [251.   246.   240.  ]
  [251.   246.   240.  ]
  ...
  [253.   249.   246.  ]
  [250.5  249.5  244.5 ]
  [253.   249.   246.  ]]

 [[251.   246.   240.  ]
  [251.   246.   240.  ]
  [251.   246.   240.  ]
  ...
  [252.   249.   244.  ]
  [253.   250.   245.  ]
  [252.5  249.25 246.  ]]], shape=(128, 128, 3), dtype=float32

tf.Tensor(
[[[104.         105.         109.        ]
  [104.9375     105.9375     109.9375    ]
  [106.         107.         111.        ]
  ...
  [ 93.          93.          93.        ]
  [ 93.          93.          95.        ]
  [ 92.          92.          90.625     ]]

 [[104.         105.         109.        ]
  [104.9375     105.9375     109.9375    ]
  [106.         107.         111.        ]
  ...
  [ 94.93359     94.93359     94.93359   ]
  [ 93.          93.          95.        ]
  [ 92.          92.          90.625     ]]

 [[105.         106.         110.        ]
  [105.         106.         110.        ]
  [107.         108.         112.        ]
  ...
  [ 94.          94.          94.        ]
  [ 94.          94.          96.        ]
  [ 92.24292     92.24292     90.86792   ]]

 ...

 [[  3.508545     2.0493164    0.        ]
  [  0.           0.72875977   0.        ]
  [  0.           0.           0.        ]
  ...
  [101.         101.         101.        ]
  [100.

tf.Tensor(
[[[ 96.97656  131.97656  153.97656 ]
  [ 97.02344  129.39844  152.27344 ]
  [101.02344  133.27344  158.27344 ]
  ...
  [ 85.15625  114.15625  131.90625 ]
  [ 87.53125  116.53125  134.53125 ]
  [ 96.46875  123.71875  142.59375 ]]

 [[110.15625  146.15625  168.15625 ]
  [114.640625 148.26562  173.26562 ]
  [115.33594  149.33594  174.33594 ]
  ...
  [ 77.21875  106.21875  124.21875 ]
  [ 93.91406  122.91406  140.91406 ]
  [ 82.86719  111.86719  129.86719 ]]

 [[129.60938  164.60938  186.60938 ]
  [110.53906  145.53906  167.53906 ]
  [103.140625 137.14062  162.14062 ]
  ...
  [ 88.609375 119.609375 137.60938 ]
  [ 93.28906  122.28906  140.28906 ]
  [ 70.046875  99.046875 117.046875]]

 ...

 [[189.79688  189.79688  191.79688 ]
  [195.29688  195.29688  197.29688 ]
  [184.64844  184.64844  186.64844 ]
  ...
  [138.78125  138.78125  138.78125 ]
  [115.16406  116.71875  113.17969 ]
  [155.07031  157.07031  156.07031 ]]

 [[182.125    186.125    189.125   ]
  [191.08594  192.08594  1

tf.Tensor(
[[[222.0039    214.0039    192.9961   ]
  [219.00781   213.00781   189.00781  ]
  [218.01172   212.01172   190.0039   ]
  ...
  [ 66.99609    33.984375   14.972656 ]
  [ 45.98828    21.988281   17.988281 ]
  [ 48.003906   23.988281   19.988281 ]]

 [[222.03516   216.03516   192.0586   ]
  [221.02344   215.02344   191.02344  ]
  [223.        217.        191.02344  ]
  ...
  [ 63.046875   23.058594   13.       ]
  [ 43.035156   16.035156    9.011719 ]
  [ 53.023438   23.023438   13.0234375]]

 [[226.01953   221.01953   202.01953  ]
  [227.01953   220.01953   201.01953  ]
  [226.        220.        198.       ]
  ...
  [ 69.         27.         13.       ]
  [ 41.960938   14.9609375   7.9609375]
  [ 51.98047    21.980469   11.980469 ]]

 ...

 [[244.        228.        213.       ]
  [243.        227.        212.       ]
  [243.        225.        211.       ]
  ...
  [200.9414    212.9414    226.9414   ]
  [206.        218.        232.       ]
  [204.88281   218.92188   231.92

tf.Tensor(
[[[238.65625  225.       211.48438 ]
  [218.82812  196.34375  162.51562 ]
  [237.6875   213.6875   178.03125 ]
  ...
  [154.42188  140.25     110.90625 ]
  [209.79688  183.79688  158.79688 ]
  [219.51562  202.51562  174.17188 ]]

 [[228.       222.       198.      ]
  [229.51562  210.51562  178.51562 ]
  [242.45312  217.42188  182.90625 ]
  ...
  [143.03125  127.03125   93.03125 ]
  [198.90625  173.90625  142.90625 ]
  [176.45312  162.96875  127.96875 ]]

 [[218.70312  209.125    181.98438 ]
  [214.5625   190.5625   154.5625  ]
  [231.5625   200.70312  147.26562 ]
  ...
  [101.265625  91.984375  60.84375 ]
  [186.75     171.46875  142.60938 ]
  [177.01562  173.875    140.59375 ]]

 ...

 [[248.71875  245.71875  236.71875 ]
  [248.85938  244.85938  235.85938 ]
  [250.60938  243.60938  235.60938 ]
  ...
  [199.42188  191.42188  168.42188 ]
  [248.59375  240.59375  221.3125  ]
  [240.85938  236.29688  225.29688 ]]

 [[248.60938  240.64062  232.15625 ]
  [237.90625  229.9375   2

tf.Tensor(
[[[253.375   249.1294  249.36938]
  [251.8894  246.875   236.78003]
  [220.07812 212.07812 183.26562]
  ...
  [165.01562 175.01562 187.01562]
  [167.9231  177.9231  189.9231 ]
  [166.01001 172.01001 186.01001]]

 [[255.      253.35938 242.98315]
  [212.15625 198.0625  178.01562]
  [186.01562 171.01562 137.97827]
  ...
  [164.95312 174.95312 186.9436 ]
  [167.01562 176.97241 188.96875]
  [171.      177.      191.     ]]

 [[241.40625 236.99683 230.32812]
  [196.97827 173.82202 146.67188]
  [200.85962 178.7815  148.85962]
  ...
  [169.98413 177.98413 188.98413]
  [170.77173 178.77173 189.77173]
  [172.40942 178.40942 192.40942]]

 ...

 [[208.72485 203.72485 209.72485]
  [206.75122 201.75122 207.75122]
  [205.07812 200.07812 206.07812]
  ...
  [156.8606  161.65747 171.92285]
  [163.22827 167.22827 178.22827]
  [162.63794 162.63794 174.63794]]

 [[206.2981  201.2981  207.2981 ]
  [207.98804 202.98804 208.98804]
  [219.65625 214.65625 220.65625]
  ...
  [179.25    184.00952 195.

tf.Tensor(
[[[ 75.8125    80.8125   112.578125]
  [ 69.75      73.75      99.5     ]
  [ 72.9375    77.9375    99.9375  ]
  ...
  [ 63.625     76.625    118.625   ]
  [ 66.        81.875    136.4375  ]
  [ 61.1875    78.1875   130.1875  ]]

 [[ 72.41406   77.3125    99.28906 ]
  [ 66.6875    67.6875    87.578125]
  [ 81.875     86.875    118.50781 ]
  ...
  [ 63.125     76.125    120.125   ]
  [ 66.        81.875    136.4375  ]
  [ 62.085938  79.08594  131.08594 ]]

 [[ 67.69531   66.9375    90.82031 ]
  [ 79.03125   85.28125  118.765625]
  [ 85.8125    93.765625 132.82031 ]
  ...
  [ 63.414062  76.78906  120.609375]
  [ 65.875     81.890625 136.24219 ]
  [ 59.625     76.625    128.625   ]]

 ...

 [[110.58594  133.33594  200.08594 ]
  [125.5      149.25     211.      ]
  [121.05469  142.05469  207.17969 ]
  ...
  [ 22.132812  25.132812  44.132812]
  [ 23.5       25.5       46.75    ]
  [ 28.859375  30.734375  56.109375]]

 [[113.5625   134.5625   199.5625  ]
  [107.49219  128.49219  1

tf.Tensor(
[[[ 29.        31.        80.      ]
  [ 31.        32.        86.      ]
  [ 32.        33.        89.      ]
  ...
  [ 68.        93.        53.      ]
  [ 69.03125   91.734375  52.75    ]
  [ 69.9375    89.9375    52.9375  ]]

 [[ 32.        33.796875  85.40625 ]
  [ 29.        31.        80.      ]
  [ 29.        31.        80.      ]
  ...
  [ 74.609375 101.21875   51.4375  ]
  [ 75.921875 100.09375   53.703125]
  [ 71.8125    97.1875    55.375   ]]

 [[ 33.        34.        90.      ]
  [ 31.        33.        81.      ]
  [ 29.        31.        79.      ]
  ...
  [ 75.25     103.        52.      ]
  [ 77.       104.        53.      ]
  [ 76.       103.        50.      ]]

 ...

 [[ 75.125     60.125     37.125   ]
  [ 81.65625   61.90625   34.15625 ]
  [ 50.140625  36.203125  19.59375 ]
  ...
  [170.625    159.       113.3125  ]
  [170.375    163.375    119.71875 ]
  [189.28125  183.25     141.875   ]]

 [[ 54.84375   39.5625    22.953125]
  [ 41.140625  32.109375  

tf.Tensor(
[[[143.84604   184.84604   214.84604  ]
  [ 97.73285   134.02487   141.05316  ]
  [137.72018   181.72018   220.72018  ]
  ...
  [164.39761   199.39761   227.39761  ]
  [149.04593   186.04593   215.04593  ]
  [158.10574   195.10574   224.10574  ]]

 [[111.91748   157.02591   186.01904  ]
  [131.3331    174.78232   205.43466  ]
  [162.0368    203.0368    235.0368   ]
  ...
  [152.1618    187.1618    215.1618   ]
  [131.99472   168.99472   197.99472  ]
  [134.30469   171.30469   200.08783  ]]

 [[ 97.74652   135.74652   148.74652  ]
  [139.5993    181.98828   214.88672  ]
  [154.3789    190.3789    224.3789   ]
  ...
  [148.76352   183.76352   213.76352  ]
  [130.39212   162.9429    182.84134  ]
  [107.520355  137.52036   148.52036  ]]

 ...

 [[ 89.90427   102.994934   65.90427  ]
  [ 83.306366   98.0611     43.551636 ]
  [ 67.57666    82.57666    16.394226 ]
  ...
  [ 19.563873   19.563873    9.563873 ]
  [ 52.681335   50.681335   35.681335 ]
  [ 86.34897    80.34897    56.18

tf.Tensor(
[[[ 66.5      63.5      45.0625 ]
  [ 57.34375  54.34375  39.34375]
  [ 64.9375   61.9375   45.5    ]
  ...
  [ 75.75     72.75     54.875  ]
  [ 67.875    65.875    43.4375 ]
  [ 68.75     65.75     47.3125 ]]

 [[115.5     112.5      95.8125 ]
  [119.      116.      101.     ]
  [106.5     103.34375  88.8125 ]
  ...
  [ 55.4375   52.28125  37.90625]
  [ 46.75     42.75     31.21875]
  [ 52.375    48.375    37.6875 ]]

 [[ 13.       13.        5.     ]
  [159.      156.      139.     ]
  [ 15.59375  15.59375   7.59375]
  ...
  [ 19.1875   19.1875    9.1875 ]
  [ 18.1875   20.1875    9.1875 ]
  [ 18.78125  19.78125  11.78125]]

 ...

 [[163.      164.      158.     ]
  [155.1875  158.1875  151.1875 ]
  [ 84.8125   79.8125   73.8125 ]
  ...
  [193.40625 194.40625 189.40625]
  [193.59375 193.59375 193.59375]
  [191.      192.      187.     ]]

 [[161.      162.      156.     ]
  [137.15625 134.15625 125.15625]
  [ 94.5      89.5      83.5    ]
  ...
  [196.375   197.375   192.

tf.Tensor(
[[[ 80.54791    84.75104    25.954163 ]
  [ 83.27655    74.63513     4.559387 ]
  [ 82.961      71.91797     8.093811 ]
  ...
  [ 58.083313   46.083313   24.083313 ]
  [ 55.78125    44.78125    25.398438 ]
  [ 36.121643   30.138306   15.551331 ]]

 [[ 65.34766    67.71094     5.2460938]
  [ 96.67969    88.529724    6.6516724]
  [ 98.36725    85.066345    8.257874 ]
  ...
  [ 71.6991     52.222534   27.484253 ]
  [ 55.882812   42.492188   27.664062 ]
  [ 65.015625   62.5578     61.619568 ]]

 [[ 66.953186   66.359436    1.2435303]
  [108.36322    99.29303     3.6210327]
  [115.375     106.94922     9.533752 ]
  ...
  [ 91.44531    70.06641    26.760315 ]
  [ 50.390625   37.98047    17.210938 ]
  [111.9762    113.012695  113.03998  ]]

 ...

 [[179.79291   167.01166   104.42572  ]
  [184.01929   164.58179   111.19116  ]
  [130.38452   135.17609    66.44061  ]
  ...
  [166.57672   160.59235   109.706726 ]
  [154.08612   144.50793    97.5979   ]
  [161.60162   167.02094    81.55

tf.Tensor(
[[[ 36.75  35.75  41.75]
  [ 35.25  35.25  43.25]
  [ 34.    34.    42.  ]
  ...
  [ 63.    49.    48.  ]
  [ 66.25  51.5   48.5 ]
  [ 85.5   61.5   49.5 ]]

 [[ 35.25  35.25  43.25]
  [ 36.    36.    44.  ]
  [ 35.    35.    43.  ]
  ...
  [ 69.    51.75  45.5 ]
  [ 73.75  54.75  48.5 ]
  [ 93.25  67.25  53.75]]

 [[ 34.75  34.75  42.75]
  [ 34.25  34.25  42.25]
  [ 35.75  35.75  43.75]
  ...
  [ 77.25  58.    50.5 ]
  [ 89.5   66.5   52.5 ]
  [ 97.    69.75  53.5 ]]

 ...

 [[145.25 129.25 113.25]
  [143.75 131.75 109.75]
  [145.75 133.75 111.75]
  ...
  [110.75 103.75  85.75]
  [115.25 108.25  92.25]
  [112.   103.    86.  ]]

 [[143.25 127.25 111.25]
  [141.25 128.25 109.25]
  [146.   131.   110.  ]
  ...
  [110.75 103.75  87.75]
  [106.75  99.75  83.75]
  [108.5  100.75  87.  ]]

 [[147.75 131.75 115.75]
  [150.   135.   114.  ]
  [144.25 129.25 108.25]
  ...
  [109.75 103.75  91.75]
  [105.    97.5   84.25]
  [107.   101.    87.  ]]], shape=(128, 128, 3), dtype=float32